/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI01;

import javax.swing.JOptionPane;

/**
 *
 * @author rezab
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileBtn = new javax.swing.JMenu();
        menuOpenFileBtn = new javax.swing.JMenuItem();
        menuExitBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAboutMeBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dekstopPaneLayout = new javax.swing.GroupLayout(dekstopPane);
        dekstopPane.setLayout(dekstopPaneLayout);
        dekstopPaneLayout.setHorizontalGroup(
            dekstopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        dekstopPaneLayout.setVerticalGroup(
            dekstopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        fileBtn.setText("File");

        menuOpenFileBtn.setText("Open File");
        menuOpenFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenFileBtnActionPerformed(evt);
            }
        });
        fileBtn.add(menuOpenFileBtn);

        menuExitBtn.setText("Exit");
        menuExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitBtnActionPerformed(evt);
            }
        });
        fileBtn.add(menuExitBtn);

        jMenuBar1.add(fileBtn);

        jMenu2.setText("About");

        menuAboutMeBtn.setText("About Me");
        menuAboutMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutMeBtnActionPerformed(evt);
            }
        });
        jMenu2.add(menuAboutMeBtn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitBtnActionPerformed
        // TODO add your handling code here:
        int answer2=JOptionPane.showOptionDialog(this,"Do you want to Exit?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(answer2 == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this,"Program will Exit");
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitBtnActionPerformed

    private void menuAboutMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutMeBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"This program author is Yudhistira");
    }//GEN-LAST:event_menuAboutMeBtnActionPerformed

    private void menuOpenFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenFileBtnActionPerformed
        // TODO add your handling code here:
        InternalFrame frm = new InternalFrame();
        dekstopPane.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuOpenFileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstopPane;
    private javax.swing.JMenu fileBtn;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAboutMeBtn;
    private javax.swing.JMenuItem menuExitBtn;
    private javax.swing.JMenuItem menuOpenFileBtn;
    // End of variables declaration//GEN-END:variables
}
