/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI01.Project;

import GUI01.Project.Authentication.Login;
import GUI01.Project.Authentication.Register;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Box;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Yudhistira Fauzy
 */


public class Main extends javax.swing.JFrame {
    
    public static HashMap<String, User> userLogin = new HashMap<>();
    
    public static User authenticatedUser = null;

    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
        this.loadGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        listGamePane = new javax.swing.JPanel();
        purchasedGamePane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        loginForm = new javax.swing.JMenuItem();
        registerMenu = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton7.setText("Checkout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listGamePaneLayout = new javax.swing.GroupLayout(listGamePane);
        listGamePane.setLayout(listGamePaneLayout);
        listGamePaneLayout.setHorizontalGroup(
            listGamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        listGamePaneLayout.setVerticalGroup(
            listGamePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        purchasedGamePane.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(listGamePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(purchasedGamePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchasedGamePane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(listGamePane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Auth");

        loginForm.setText("Login");
        loginForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFormActionPerformed(evt);
            }
        });
        jMenu2.add(loginForm);

        registerMenu.setText("Register");
        registerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMenuActionPerformed(evt);
            }
        });
        jMenu2.add(registerMenu);

        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        jMenu2.add(logoutMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(authenticatedUser == null) {
            Alert.showMessageError(this, "Please login first to purchase!");
            return;
        }
        System.out.println(checkOutList.size() + "");
        double totalPrice = 0;
        for(GameObject checkout : checkOutList) {
            totalPrice += checkout.getPrice();
        } 
        System.out.println("Total Price: " + totalPrice);
        System.out.println("Hello mr. " + authenticatedUser.getFullName());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void loginFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFormActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        JLayeredPane pane = getLayeredPane();
        pane.add(login, Integer.valueOf(50));
        login.setVisible(true);
    }//GEN-LAST:event_loginFormActionPerformed

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure to logout?", "Logout", JOptionPane.OK_CANCEL_OPTION);
        if(answer != JOptionPane.YES_OPTION) {
            return;
        }
        if(authenticatedUser != null) {
            Main.authenticatedUser = null;
            Alert.showMessageSuccess(this, "Successfully logged out");
        } else {
            Alert.showMessageError(this, "You are not logged in");
        }
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void registerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMenuActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
        JLayeredPane pane = getLayeredPane();
        pane.add(register);
        register.setVisible(true);
    }//GEN-LAST:event_registerMenuActionPerformed

    public void loadGame() {
        listGamePane.setLayout(new GridLayout(0, 3, 3, 3));
        ArrayList<GameObject> games = new ArrayList() {
            {
                add(new GameObject("MINECRAFT", 5000, "C:\\Users\\rezab\\Downloads\\download.jpeg"));
                add(new GameObject("VALORANT", 4000));
                add(new GameObject("CSGO", 10000, "C:\\Users\\rezab\\Downloads\\csgo.jpeg"));
                add(new GameObject("FIFA", 30000));
            }
        };
        for(GameObject game : games) {
            
            JButton gameBtn = new JButton();
            gameBtn.setLayout(new BoxLayout(gameBtn, BoxLayout.Y_AXIS));
            gameBtn.add(Box.createVerticalGlue());
            if(game.getImage() != null) {
                Image img = new ImageIcon(game.getImage()).getImage();
                Image scaledImg = img.getScaledInstance(64, 64, Image.SCALE_SMOOTH);
                gameBtn.add(new JLabel(new ImageIcon(scaledImg)));
            }
            gameBtn.addActionListener((ActionEvent e) -> {
                this.addGame(game);
            });
            gameBtn.add(new JLabel(game.getName(), SwingConstants.CENTER));
            gameBtn.add(new JLabel("Rp. " + Utils.formatNumber(game.getPrice()), SwingConstants.CENTER));
            listGamePane.add(gameBtn);
        }
    }
    
    public void addGame(GameObject game) {
        if(!checkOutList.contains(game)) {
            checkOutList.add(game);
        } else {
            Alert.showMessageError(this, "You already have this game added");
        }
        this.reloadPurchasedGame();
    }
    
    public void removeGame(GameObject game) {
        if(checkOutList.contains(game)) {
            checkOutList.remove(game);
        }
        this.reloadPurchasedGame();
    }
    
    public void reloadPurchasedGame() {
        purchasedGamePane.removeAll();
        purchasedGamePane.setLayout(new GridLayout(5, 0, 5, 0));
        for(GameObject s : checkOutList) {
            JButton btn = new JButton();
            btn.addActionListener((ActionEvent e) -> {
                this.removeGame(s);
            });
            btn.setLayout(new BoxLayout(btn, BoxLayout.Y_AXIS));
            btn.add(Box.createVerticalGlue());
            btn.add(new JLabel(s.getName()));
            
            btn.add(new JLabel("Rp. " + Utils.formatNumber(s.getPrice())));
            purchasedGamePane.add(btn);
        }
        purchasedGamePane.revalidate();
        purchasedGamePane.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private final ArrayList<GameObject> checkOutList = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel desktopPane;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel listGamePane;
    private javax.swing.JMenuItem loginForm;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JPanel purchasedGamePane;
    private javax.swing.JMenuItem registerMenu;
    // End of variables declaration//GEN-END:variables
}
